version: "3"

services:
  redis:
    image: redis:3
    networks:
      - local

  reader:
    image: daocloud.io/wubo19842008/msg-reader
    networks:
      - local
    environment:
      SPRING_REDIS_HOST: redis

  writer:
    image: daocloud.io/wubo19842008/msg-writer
    networks:
      - local
    environment:
      SPRING_REDIS_HOST: redis

networks:
  local: